version: "3.9"

services:
  Fereira.Costa.server:
    image: ${DOCKER_REGISTRY:-}developerevaluationserver
    build:
      context: .
      dockerfile: Fereira.Costa.Server/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - SqlServer=Server=sqlserver;Database=AmbevDb;User Id=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=True;MultipleActiveResultSets=True
    depends_on:
      - sqlserver
    restart: always
    networks:
      - app-backend
      - app-frontend
    links:
      - sqlserver

  Fereira.Costa.client:
    image: ${DOCKER_REGISTRY:-}developerevaluationclient
    build:
      context: ./Fereira.Costa.client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./Fereira.Costa.client:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - DEV_SERVER_PORT=5173
    depends_on:
      - Fereira.Costa.server
    networks:
      - app-frontend
    links:
      - Fereira.Costa.server

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Passw0rd
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql
    networks:
      - app-backend

networks:
  app-backend: {}
  app-frontend: {}

volumes:
  sqlserver-data:
