deploy:
  runs-on: ubuntu-latest
  needs: build
  env:
    DATABASE_URI: ${{ secrets.DATABASE_URI }}
    WEBSITE_CORS_SUPPORT_CREDENTIALS: "True"
    PORT: "8080"
  steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v4
      with:
        name: .net-app

    - name: Login to Azure
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: "fereira-costa-api"
        slot-name: "Production"
        package: .

    - name: Set Startup Command
      run: |
        az webapp config set \
          --name "fereira-costa-api" \
          --resource-group "fereira-costa" \
          --startup-file "dotnet Fereira.Costa.Server.dll"
